apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: claim-noop-checkin-pipeline
spec:
  params:
  - name: clusterpool-name
    type: string
    description: The name of the ClusterPool from which you want to claim a cluster.  
  - name: clusterclaim-name
    type: string
    description: The name of the ClusterClaim that will be created against your ClusterPool
  - name: clusterpool-namespace
    type: string
    description: The namespace that holds your ClusterPools
  - name: clusterpool-group
    type: string
    description: An RBAC group that has access to your ClusterPools
  tasks:
    - name: cluster-claim
      taskRef:
        name: cm-clusterpool-claim
      params:
      - name: clusterpool-name
        value: "$(params.clusterpool-name)"
      - name: clusterclaim-name
        value: "$(params.clusterclaim-name)"
      - name: clusterpool-namespace
        value: "$(params.clusterpool-namespace)"
      - name: clusterpool-group
        value: "$(params.clusterpool-group)"
    - name: cluster-login
      params:
      - name: username
        value: "$(tasks.cluster-claim.results.username)"
      - name: password
        value: "$(tasks.cluster-claim.results.password)"
      - name: api
        value: "$(tasks.cluster-claim.results.api)"
      taskRef:
        name: login-to-cluster
      runAfter:
        - cluster-claim
    - name: cluster-checkin
      taskRef:
        name: cm-clusterpool-checkin
      params:
      - name: clusterclaim-name
        value: "$(params.clusterclaim-name)"
      - name: clusterpool-namespace
        value: "$(params.clusterpool-namespace)"
      - name: clusterpool-group
        value: "$(params.clusterpool-group)"
      runAfter:
        - cluster-login
