apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cm-clusterpool-checkin
  labels:
    app.kubernetes.io/version: "0.0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Kubernetes
    tekton.dev/tags: "aws, openshift, rhacm"
    tekton.dev/displayName: "cm ClusterPool Checkin"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: |
    Deletes a ClusterClaim on an ACM/OCM ClusterPool.  

    This task can be used to delete a clusterclaim from a ClusterPool created on an ACM/OCM Hub cluster.  
  params:
  - name: clusterclaim-name
    type: string
    description: The name of the ClusterClaim that will be created against your ClusterPool
  - name: clusterpool-namespace
    type: string
    description: The namespace that holds your ClusterPools
  - name: clusterpool-group
    type: string
    description: An RBAC group that has access to your ClusterPools
  steps:
  - name: write-kubeconfig
    image: quay.io/gurnbenibm/cm:latest
    script: |
      echo "Setting up the local cluster as a ClusterPoolHost with which to interact."
      # We have to oc login due to limitations in 'cm create cph'
      set +x
      oc login `oc whoami --show-console | sed 's/console-openshift-console.apps/api/g'`:6443 \
        --token=`cat /var/run/secrets/kubernetes.io/serviceaccount/token` \
        --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      set -x
      cm create clusterpoolhost tek-hub --api-server=`oc whoami --show-console | sed 's/console-openshift-console.apps/api/g'`:6443 --console=`oc whoami --show-console` --group $(params.clusterpool-group) --namespace $(params.clusterpool-namespace)
      echo "Deleting ClusterClaim named $(params.clusterclaim-name)."
      cm delete clusterclaim $(params.clusterclaim-name)
