kind: ServiceAccount
apiVersion: v1
metadata:
  name: cm-claim-cluster-sa
  namespace: ci
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin
subjects:
  - kind: ServiceAccount
    name: cm-claim-cluster-sa
    namespace: ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cm-claimed-cluster-credentials
spec:
  resources:
    requests:
      storage: 5M
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: claim-cluster
spec:
  serviceAccountName: cm-claim-cluster-sa
  taskRef:
    name: cm-clusterpool-claim
  params:
  - name: clusterpool-name
    value: canary-aws-latest-48
  - name: clusterclaim-name
    value: cm-tekton-task-test
  - name: clusterpool-namespace
    value: clusterpool
  - name: clusterpool-group
    value: CICD
  workspaces:
  - name: credentials
    persistentVolumeClaim:
      claimName: cm-claimed-cluster-credentials
