kind: ServiceAccount
apiVersion: v1
metadata:
  name: cm-claim-cluster-sa
  namespace: ci
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin
subjects:
  - kind: ServiceAccount
    name: cm-claim-cluster-sa
    namespace: ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: checkin-cluster
spec:
  serviceAccountName: cm-claim-cluster-sa
  taskRef:
    name: cm-clusterpool-checkin
  params:
  - name: clusterclaim-name
    value: cm-tekton-task-test
  - name: clusterpool-namespace
    value: clusterpool
  - name: clusterpool-group
    value: CICD
